test terraform init

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -50,19 +50,18 @@ jobs:
     - name: Terraform init
        run:         
         terraform init
-      working-directory: ./infra
 
-    - name: Terraform plan
-      run:         
-        terraform plan
-      working-directory: ./infra
+    # - name: Terraform plan
+    #   run:         
+    #     terraform plan
+    #   working-directory: ./infra
 
-    - name: Terraform plan status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
-      working-directory: ./infra
+    # - name: Terraform plan status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
+    #   working-directory: ./infra
 
-    - name: Terraform apply
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-      run: terraform apply
-      working-directory: ./infra
+    # - name: Terraform apply
+    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+    #   run: terraform apply
+    #   working-directory: ./infra
